// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nadjqprggcpmddudhhql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hZGpxcHJnZ2NwbWRkdWRoaHFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NzI2MDUsImV4cCI6MjA3NDA0ODYwNX0.GeDAj-cccdP5GxwL0kkSYI8ArgltguGzZJmp5B1ZzJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});